name:                zoutig
version:             0.1.0.0
github:              "MennodeBoer/zoutig"
license:             BSD3
author:              "Menno de Boer"
maintainer:          "mennodeboer94@gmail.com"
copyright:           "BSD-3"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/MennodeBoer/zoutig#readme>

dependencies:
- base >= 4.7 && < 5
- base-compat
- mtl
- attoparsec 
- bytestring
- string-conversions
- time
- http-media
- http-client
- directory
- lucid
- aeson
- blaze-markup
- blaze-html
- servant
- servant-server
- servant-client
- servant-js
- stm
- language-javascript
- js-jquery
- wai
- warp
- text
- random
- containers
- async

library:
  source-dirs: src

executables:
  zoutig-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - zoutig

tests:
  zoutig-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - zoutig
